### ISSUE TITLE
📅 - Taiga UI Roadmap 2022 [Q1-Q2]

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#1197]
These are the general things that are on our plans for 2022. Keep in mind that it may change due to urgent internal needs and if time allows, items might move up the queue.

## Q1

- [x] https://github.com/Tinkoff/taiga-ui/issues/1196
- [x] https://github.com/Tinkoff/taiga-ui/issues/256
- [x] https://github.com/Tinkoff/taiga-ui/issues/414
- [x] https://github.com/Tinkoff/taiga-ui/issues/1221
- [x] https://github.com/Tinkoff/taiga-ui/issues/906
- [x] https://github.com/Tinkoff/taiga-ui/issues/928
- [x] https://github.com/Tinkoff/taiga-ui/issues/892

## Q2

- [ ] https://github.com/Tinkoff/taiga-ui/issues/917
- [x] https://github.com/Tinkoff/taiga-ui/issues/980
- [x] https://github.com/Tinkoff/taiga-ui/issues/528
- [x] https://github.com/Tinkoff/taiga-ui/issues/546
- [x] https://github.com/Tinkoff/taiga-ui/issues/673
- [x] https://github.com/Tinkoff/taiga-ui/issues/1258
- [ ] https://github.com/Tinkoff/taiga-ui/issues/553
- [x] https://github.com/Tinkoff/taiga-ui/issues/950
- [ ] https://github.com/Tinkoff/taiga-ui/issues/1302

## Q3-Q4

TBD

## Other

- [ ] https://github.com/Tinkoff/taiga-ui/issues/120
- [x] https://github.com/Tinkoff/taiga-ui/issues/133
- [ ] https://github.com/Tinkoff/taiga-ui/issues/476
- [ ] https://github.com/Tinkoff/taiga-ui/issues/1163
- [ ] https://github.com/Tinkoff/taiga-ui/issues/999

# Unspecified date for the next major release:

- [x] https://github.com/Tinkoff/taiga-ui/issues/980
- [x] https://github.com/Tinkoff/taiga-ui/issues/928
- [x] https://github.com/Tinkoff/taiga-ui/issues/906
- [x] https://github.com/Tinkoff/taiga-ui/issues/739
- [x] https://github.com/Tinkoff/taiga-ui/issues/734
- [x] https://github.com/Tinkoff/taiga-ui/issues/699
