### ISSUE TITLE
📅 - Taiga UI Roadmap 2021

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#803]
These are the general things that are on our plans for 2021. Keep in mind that it may change due to urgent internal needs.

## Q1

-   [x] addon-table
-   [x] i18n package
-   [x] Night theme
-   [x] Demo portal improvements (customization guides, edit on Stackblitz, night mode)

## Q2

-   [x] Expand components customization with DI tokens
-   [x] https://github.com/TinkoffCreditSystems/taiga-ui/issues/162
-   [x] addon-editor (WYSIWYG) improvements
-   [x] Investigate localization such as date, number formatting, rtl languages

## Q3

-   [x] https://github.com/TinkoffCreditSystems/taiga-ui/issues/258
-   [x] https://github.com/TinkoffCreditSystems/taiga-ui/issues/154
-   [x] Sheet component

## Q4

-   [x] https://github.com/TinkoffCreditSystems/taiga-ui/issues/257
-   [ ] https://github.com/TinkoffCreditSystems/taiga-ui/issues/476
-   [ ] Investigate exposing native input from controls
-   [ ] Generic notifications mechanism similar to dialogs
-   [ ] Continue customization with DI tokens
-   [ ] Continue localization improvements

## Other

-   [x] Screenshot testing on CI
-   [ ] https://github.com/TinkoffCreditSystems/taiga-ui/issues/120
-   [x] https://github.com/TinkoffCreditSystems/taiga-ui/issues/416
-   [ ] https://github.com/TinkoffCreditSystems/taiga-ui/issues/892
-   [ ] Dashboard project that shows the power of Taiga
-   [ ] 1 bugfix week per month to keep bug numbers at bay
-   [ ] 1 week per month dedicated to internal tasks

# Taiga 2022 plans (major release):

-   [ ] Expose native input from all controls
-   [ ] https://github.com/TinkoffCreditSystems/taiga-ui/issues/256
-   [ ] https://github.com/TinkoffCreditSystems/taiga-ui/issues/739
-   [ ] https://github.com/TinkoffCreditSystems/taiga-ui/issues/734
-   [ ] https://github.com/TinkoffCreditSystems/taiga-ui/issues/699

**Comment by waterplea** [comment]
It was a good year 😎
